# Path: 2025/src/day_7.py

"""
--- Day 7: Laboratories ---
You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At that point, the original beam stops, and two new beams are emitted from the splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
Those beams continue downward until they reach more splitters:

.......S.......
.......|.......
......|^|......
......|.|......
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
This process continues until all of the tachyon beams reach a splitter or exit the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|
To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?


The first half of this puzzle is complete! It provides one gold star: *

--- Part Two ---
With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
...|^.^...^....
...|...........
..|^.^...^.^...
..|............
.|^...^.....^..
.|.............
|^.^.^.^.^...^.
|..............
Or, there's the timeline where the particle alternated going left and right at each splitter:

.......S.......
.......|.......
......|^.......
......|........
......^|^......
.......|.......
.....^|^.^.....
......|........
....^.^|..^....
.......|.......
...^.^.|.^.^...
.......|.......
..^...^|....^..
.......|.......
.^.^.^|^.^...^.
......|........
Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
....^|^...^....
.....|.........
...^.^|..^.^...
......|........
..^..|^.....^..
.....|.........
.^.^.^|^.^...^.
......|........
In this example, in total, the particle ends up on 40 different timelines.

Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?
"""

from typing import Optional
from functools import cache

from loguru import logger


class Tree:
    map: list[list[str]]
    start: tuple[int, int]
    beams: dict[int, list[int]]
    hit_dividers: dict[int, list[int]]

    def __init__(self, map: list[list[str]], start: tuple[int, int]):
        self.map = map
        self.start = start
        self.beams = {0: [start[1]]}
        self.hit_dividers = {}

    @classmethod
    def from_file(cls, file_path: str) -> "Tree":
        with open(file_path, "r") as file:
            map = [list(line.strip()) for line in file.readlines()]
            # find "S" in the first line
            start = next((0, i) for i, char in enumerate(map[0]) if char == "S")
            return cls(map, start)

    def __str__(self) -> str:
        return_str = ""
        for i, row in enumerate(self.map):
            for j, char in enumerate(row):
                if (i, j) == self.start:
                    return_str += "S"
                elif i in self.beams and j in self.beams[i]:
                    return_str += "|"
                else:
                    return_str += char
            return_str += "\n"
        return return_str

    def _propagate_beams(self) -> Optional[int]:
        last_beam_level = max(self.beams.keys())
        current_beam_level = last_beam_level + 1
        if current_beam_level >= len(self.map):
            return None
        next_map_row = self.map[last_beam_level + 1]

        self.beams[current_beam_level] = []
        self.hit_dividers[current_beam_level] = []

        for beam_index in self.beams[last_beam_level]:
            if next_map_row[beam_index] == ".":
                self.beams[current_beam_level].append(beam_index)
            elif next_map_row[beam_index] == "^":
                if beam_index not in self.hit_dividers[current_beam_level]:
                    self.hit_dividers[current_beam_level].append(beam_index)
                if beam_index - 1 not in self.beams[current_beam_level]:
                    self.beams[current_beam_level].append(beam_index - 1)
                if beam_index + 1 not in self.beams[current_beam_level]:
                    self.beams[current_beam_level].append(beam_index + 1)

            else:
                raise ValueError(f"Invalid beam direction: {next_map_row[beam_index]}")

        return len(self.hit_dividers.get(current_beam_level, []))


@cache
def count_paths_from(tree_map_tuple: tuple, row: int, col: int) -> int:
    """
    Count the number of unique paths from (row, col) to any end position.
    Uses memoization to avoid recomputing.
    """
    # Convert tuple back to list for indexing
    tree_map = list(tree_map_tuple)

    # Base case: reached the end
    if row == len(tree_map):
        return 1

    # Get current cell
    current_cell = tree_map[row][col]

    if current_cell == "." or current_cell == "S":
        # Continue straight down (S acts like .)
        return count_paths_from(tree_map_tuple, row + 1, col)
    elif current_cell == "^":
        # Split into two paths
        left_paths = count_paths_from(tree_map_tuple, row + 1, col - 1)
        right_paths = count_paths_from(tree_map_tuple, row + 1, col + 1)
        return left_paths + right_paths
    else:
        raise ValueError(f"Invalid cell: {current_cell}")


def get_all_quantum_paths(tree: Tree) -> int:
    """
    Count the total number of unique quantum paths (timelines) through the tree.
    """
    # Convert map to tuple of tuples for caching
    tree_map_tuple = tuple(tuple(row) for row in tree.map)

    # Start from row 1 (row 0 contains 'S'), column is the starting column
    start_row = tree.start[0] + 1
    start_col = tree.start[1]

    logger.debug(f"Starting from position: row={start_row}, col={start_col}")

    # Count paths starting from the position after 'S'
    total_paths = count_paths_from(tree_map_tuple, start_row, start_col)

    logger.debug(f"Total unique paths: {total_paths}")

    return total_paths


# --- Part One ---


def part_1(file_path: str) -> int:
    """
    Read the input file and return the solution.
    """

    tree = Tree.from_file(file_path)
    hit_dividers = 0
    while True:
        new_hit_dividers = tree._propagate_beams()
        if new_hit_dividers is None:
            break
        hit_dividers += new_hit_dividers
    logger.debug(f"Tree:\n{tree}")
    logger.debug(f"Hit dividers: {tree.hit_dividers}")
    logger.debug(f"Beams: {tree.beams}")
    return hit_dividers


# --- Part Two ---


def part_2(file_path: str) -> int:
    """
    Read the input file and return the solution.
    """

    tree = Tree.from_file(file_path)
    return get_all_quantum_paths(tree)
